CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  government_name VARCHAR(255),
  nickname VARCHAR(60) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  country VARCHAR(100),
  profile_pic VARCHAR(255),
  wallpaper VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
